// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';
import {ovsdb} from '../models';

export function AddToHistory(arg1:main.ConnectionHistory):Promise<void>;

export function ConnectOVSDB(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:Array<string>,arg7:string):Promise<void>;

export function DeleteHistory(arg1:number):Promise<void>;

export function DisconnectOVSDB():Promise<void>;

export function GetBridges():Promise<Array<model.Bridge>>;

export function GetHistory():Promise<Array<main.ConnectionHistory>>;

export function GetInterfaces():Promise<Array<model.Interface>>;

export function GetOVSDBClient():Promise<ovsdb.OVSDBClient>;

export function GetOpenvSwitch():Promise<Array<model.OpenvSwitch>>;

export function GetPorts():Promise<Array<model.Port>>;

export function GetSchema():Promise<string>;

export function LoadHistory():Promise<void>;

export function SaveHistory():Promise<void>;
