// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToHistory(arg1) {
  return window['go']['main']['App']['AddToHistory'](arg1);
}

export function ConnectOVSDB(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ConnectOVSDB'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DeleteHistory(arg1) {
  return window['go']['main']['App']['DeleteHistory'](arg1);
}

export function DisconnectOVSDB() {
  return window['go']['main']['App']['DisconnectOVSDB']();
}

export function GetBridges() {
  return window['go']['main']['App']['GetBridges']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetInterfaces() {
  return window['go']['main']['App']['GetInterfaces']();
}

export function GetOVSDBClient() {
  return window['go']['main']['App']['GetOVSDBClient']();
}

export function GetOpenvSwitch() {
  return window['go']['main']['App']['GetOpenvSwitch']();
}

export function GetPorts() {
  return window['go']['main']['App']['GetPorts']();
}

export function GetSchema() {
  return window['go']['main']['App']['GetSchema']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadHistory() {
  return window['go']['main']['App']['LoadHistory']();
}

export function SaveHistory() {
  return window['go']['main']['App']['SaveHistory']();
}
